# Generated by Django 4.2.7 on 2023-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_keeper', '0002_plant_creator_plant_img_post_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
