# Generated by Django 4.2.7 on 2023-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_keeper', '0002_post_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
