# Generated by Django 4.2.7 on 2024-02-28 21:09

from django.db import migrations, models
import django.db.models.deletion
import schedule_keeper.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_keeper', '0003_alter_plant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=schedule_keeper.models.upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=schedule_keeper.models.upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='schedule_keeper.plant'),
        ),
    ]
